import { notFound } from "next/navigation";
import { Breadcrumbs } from "@/components/breadcrumbs";
import { isLocale, type Locale } from "@/lib/i18n";

export default async function AboutPage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale: rawLocale } = await params;
  if (!isLocale(rawLocale)) notFound();
  const locale: Locale = rawLocale;
  const c = locale === "pt"
    ? { label: "Sobre", title: "Um guia para diminuir ruído, não para vender pressa.", intro: "O DevAtlas organiza áreas, fundamentos e projetos de tecnologia em caminhos que podem ser questionados, comparados e adaptados.", principles: "Princípios editoriais", body: ["Fundamentos antes de ferramentas. Uma tecnologia só aparece com contexto de uso, limites e alternativas.", "Projetos pequenos, completos e explicáveis valem mais que clones enormes sem decisão própria.", "Carreira não é uma linha reta. Experiência anterior, contexto local, tempo e interesse mudam o melhor caminho.", "O conteúdo evita estimativas salariais sem fonte e não transforma tendência em regra."], architecture: "Como o conteúdo é organizado", archBody: "Áreas, tecnologias, linguagens, frameworks, ferramentas, bancos, serviços cloud, carreiras, roadmaps, projetos, certificações, glossário, comparações e trilhas vivem em coleções tipadas. As páginas apenas combinam esses registros, evitando repetição e facilitando tradução." }
    : locale === "en"
      ? { label: "About", title: "A guide to reduce noise, not sell urgency.", intro: "DevAtlas organizes technology fields, foundations and projects into paths that can be questioned, compared and adapted.", principles: "Editorial principles", body: ["Foundations before tools. Technology only appears with use context, limits and alternatives.", "Small, complete and explainable projects beat huge clones without original decisions.", "Careers are not straight lines. Previous experience, local context, time and interest change the best path.", "Content avoids unsourced salary estimates and never turns a trend into a rule."], architecture: "How content is organized", archBody: "Fields, technologies, languages, frameworks, tools, databases, cloud services, career paths, roadmaps, projects, certifications, glossary terms, comparisons and learning paths live in typed collections. Pages combine records instead of repeating them, making translation easier." }
      : { label: "Acerca de", title: "Una guía para reducir ruido, no para vender prisa.", intro: "DevAtlas organiza áreas, fundamentos y proyectos en caminos que se pueden cuestionar, comparar y adaptar.", principles: "Principios editoriales", body: ["Fundamentos antes que herramientas. Una tecnología aparece con contexto, límites y alternativas.", "Proyectos pequeños, completos y explicables valen más que clones enormes sin decisiones propias.", "La carrera no es una línea recta. Experiencia, contexto, tiempo e interés cambian el mejor camino.", "El contenido evita salarios sin fuente y no convierte tendencias en reglas."], architecture: "Cómo se organiza el contenido", archBody: "Áreas, tecnologías, lenguajes, frameworks, herramientas, bases, cloud, carreras, roadmaps, proyectos, certificaciones, glosario, comparaciones y rutas viven en colecciones tipadas. Las páginas combinan registros, evitando repetición y facilitando traducción." };
  return <div className="page-shell"><header className="page-hero"><Breadcrumbs locale={locale} items={[{ label: c.label }]} /><span className="eyebrow">{c.label}</span><h1>{c.title}</h1><p>{c.intro}</p></header><article className="prose article-narrow"><h2>{c.principles}</h2><ul>{c.body.map((item) => <li key={item}>{item}</li>)}</ul><h2 id="collections">{c.architecture}</h2><p>{c.archBody}</p></article></div>;
}
